//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.foxmail.wyyuan1991.TicketInfoCrawler.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.foxmail.wyyuan1991.TicketInfoCrawler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BXP,ZAP,2015-05-01
        ///ZAP,GMP,2015-05-01
        ///GMP,BMP,2015-05-01
        ///BMP,DOP,2015-05-01
        ///DOP,ZHP,2015-05-01
        ///ZHP,SJP,2015-05-01
        ///SJP,GNP,2015-05-01
        ///GNP,EDP,2015-05-01
        ///EDP,HPP,2015-05-01
        ///HPP,ADF,2015-05-01
        ///ADF,HFF,2015-05-01
        ///HFF,EGF,2015-05-01
        ///EGF,ZAF,2015-05-01
        ///ZAF,XVF,2015-05-01
        ///XVF,LBN,2015-05-01
        ///LBN,ZLN,2015-05-01
        ///ZLN,MDN,2015-05-01
        ///MDN,OYN,2015-05-01
        ///OYN,XJN,2015-05-01
        ///XJN,WHN,2015-05-01
        ///WHN,XRN,2015-05-01
        ///XRN,CIN,2015-05-01
        ///CIN,YIQ,2015-05-01
        ///YIQ,MQQ,2015-05-01
        ///MQQ,CWQ,2015-05-01
        ///CWQ,ZAQ,2015 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
    }
}
